AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Nested application resources

Parameters:
  PROJECT:
    Type: String
    Default: VANDAL

  ENV:
    Type: String
    Default: "Stage"

Resources:
  RestApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest_api/template.yaml
      Parameters:
        ENV: !Ref ENV
        TABLELAYERS: !Sub "${PROJECT}-${ENV}-ArtworkLayersTable"
        TABLEMESSAGES: !Sub "${PROJECT}-${ENV}-WebsocketMessagesTable"
        BUCKETIMAGES: !Sub "${PROJECT}-${ENV}-images-bucket"

  WebSocketApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: websocket_api/template.yaml
      Parameters:
        ENV: !Ref ENV
        TABLEMESSAGES: !Sub "${PROJECT}-${ENV}-WebsocketMessagesTable"
        TABLECONNECTIONS: !Sub "${PROJECT}-${ENV}-WebsocketConnectionsTable"
    DependsOn: RestApi

Outputs:
  RestApiUrl:
    Description: REST API URL
    Value: !GetAtt RestApi.Outputs.ApiUrl

  WebSocketApiUri:
    Description: WebSocket API URI
    Value: !GetAtt WebSocketApi.Outputs.WebSocketURI
