AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Nested application resources

Parameters:
  PROJECT:
    Type: String
    Default: VANDAL

  ENV:
    Type: String
    Default: "Stage"

Resources:
  WebSocketApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: websocket_api/template.yaml
      Parameters:
        ENV: !Ref ENV
        TABLEMESSAGES: !Sub "${PROJECT}-${ENV}-WebsocketMessagesTable"
        TABLECONNECTIONS: !Sub "${PROJECT}-${ENV}-WebsocketConnectionsTable"

  RestApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: rest_api/template.yaml
      Parameters:
        ENV: !Ref ENV
        TABLELAYERS: !Sub "${PROJECT}-${ENV}-ArtworkLayersTable"
        TABLEMESSAGES: !Sub "${PROJECT}-${ENV}-WebsocketMessagesTable"
        BUCKETIMAGES: !Sub "vandal-stage-images-bucket"
        WEBSOCKETURI: !GetAtt WebSocketApi.Outputs.WebSocketURI
    DependsOn: WebSocketApi

Outputs:
  WebSocketApiUri:
    Description: WebSocket API URI
    Value: !GetAtt WebSocketApi.Outputs.WebSocketURI

  RestApiUrl:
    Description: REST API URL
    Value: !GetAtt RestApi.Outputs.ApiUrl

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt RestApi.Outputs.CognitoUserPoolId

  CognitoAppClientId:
    Description: Cognito App Client ID
    Value: !GetAtt RestApi.Outputs.CognitoAppClientId
