AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: REST API for Vandal

Parameters:
  PROJECT:
    Type: String
    Default: VANDAL

  ENV:
    Type: String
    Default: Stage
    AllowedValues:
      - Dev
      - Stage
      - Prod

  TABLELAYERS:
    Type: String
    Default: VANDAL-Stage-ArtworkLayersTable

  TABLEMESSAGES:
    Type: String
    Default: VANDAL-Stage-WebsocketMessagesTable

  BUCKETIMAGES:
    Type: String
    Default: VANDAL-Stage-images-bucket

Resources:
  restApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${PROJECT}-${ENV}-restApiFunction
      Description: FastAPI with Mangum handler
      MemorySize: 128
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.9
      Timeout: 300
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TABLELAYERS
        - DynamoDBCrudPolicy:
            TableName: !Ref TABLEMESSAGES
      Environment:
        Variables:
          ENV: !Ref ENV
          DB_TABLE_LAYERS: !Ref TABLELAYERS
          DB_TABLE_MESSAGES: !Ref TABLEMESSAGES
          S3_BUCKET_IMAGES: !Ref BUCKETIMAGES
      Events:
        DefaultEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  LayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TABLELAYERS
      AttributeDefinitions:
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: layer_type
          AttributeType: S
        - AttributeName: base_layer_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      # BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: layer_type_index
          KeySchema:
            - AttributeName: layer_type
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: base_layer_id_index
          KeySchema:
            - AttributeName: base_layer_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${PROJECT}-${ENV}-RestApiGateway
      StageName: !Ref ENV
      OpenApiVersion: "3.0.2"

Outputs:
  ApiUrl:
    Description: URL of the API
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${ENV}
    Export:
      Name: ApiUrl
